#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "apt"
cookbook "build-essential"
cookbook "git"
cookbook "nginx"
cookbook "rbenv", github: "fnichol/chef-rbenv"
cookbook "ruby_build"
cookbook "vim"
cookbook "xml"
